services:
  web-app:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: steganoweb-ui
    restart: always
    ports:
      - "70:3000"
    volumes:
      - /srv/steganoweb/web:/app
      - /app/node_modules
      - ${HOSTS_CONFIG:-./config/hosts.conf}:/etc/hosts.extra:ro
    environment:
      - NODE_ENV=development
    depends_on:
      - api
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://127.0.0.1:3000 || exit 1"
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 10s

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: steganoweb-api
    ports:
      - "71:5000"
    restart: always
    volumes:
      - /srv/steganoweb/api:/app
      - /srv/steganoweb/main.py:/app/main.py  # Mount main.py directly
      - ${HOSTS_CONFIG:-./config/hosts.conf}:/etc/hosts.extra:ro
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - MAIN_PY_PATH=/app/main.py
    healthcheck:
      test: "bash -c 'echo -n > /dev/tcp/127.0.0.1/5000'"
      interval: 1m30s
      timeout: 5s
      retries: 3
      start_period: 5s
